### PR TITLE
Emoji shortcodes

### LINKED ISSUE #109: Replace scrubbed emojis with :emoji name:
To mitigate #55 I decided to replace all emoji with a cabal unicode character (hehe)

@cinnamon-bun had the great idea of finding a node module to replace the emojis with their name in text, like `:star:`. Which is fantastic!

### Implementation
* [ ] Find modules that do map emojis to their text representations
* [ ] Replace unicode emojis with their text!

### PR DESCRIPTION
**Pull request by fenwick67**
Should fix #109 after much discussion

### CODE REVIEW

**Comment by noffle** [comment]
Yay thank you @fenwick67 :heart:

Do you have the time & space to write a simple unit test for this? Just something that runs the sanitizer function against some strings with emoji and confirming that we get the shortcodes out.

**Comment by fenwick67** [comment]
@noffle can do

**Comment by cblgh** [comment]
dooooooooooooope! thank you @fenwick67!

**Comment by noffle** [comment]
Thank you @fenwick67 :tada:

**Pull request merged**
