### PR TITLE
Sort hidden users to bottom of user pane, prefix their names with minus sign

### PR DESCRIPTION
**Pull request by cblgh**
this pr sorts hidden users to the bottom of the user pane (probably dont want someone you've hidden to be in yr face). 

their names are also prefixed with a minus sign; eases the amount of mental accounting you need to do to know who is banned & not. see image below for demo

Screen Shot 2020-06-05 at 11 02 57

this PR also greatly improves the styling of applied moderation messages, which are virtual messages with type `chat/moderation`. see image below

image

### CODE REVIEW

**Comment by cblgh** [comment]
_if you have mod, khajit has bans_

**Comment by okdistribute** [comment]
Can someone change their name to something offensive and still be visible? Is there a way to hide banned users completely?

**Comment by cblgh** [comment]
@okdistribute yes. one thing i was considering was the following:
* keep the first three letters of the nick, erase the rest and replace with the first 6 characters of their public key
* stop propagating updates in cabal-client from

**Comment by cblgh** [comment]
tracking yr concerns in this issue here https://github.com/cabal-club/cabal-cli/issues/193 @okdistribute, i'll try to add that in a couple of future PRs and focus on first landing the work i already have in the pipeline :)

**Pull request merged**
