### PR TITLE
Add shift+pgup/down for nick scrolling and faster message scrolling

### PR DESCRIPTION
**Pull request by fabianhjr**
Blocked by upstream dependency: https://github.com/mafintosh/neat-input/pull/11/

### CODE REVIEW

**Comment by noffle** [comment]
If there are no objections, I'd be ok with just remapping page {up,down} to do page-fulls of scrollback. I find the current behaviour of page {up,down} moving one line to be inconsistent with every other program I've used (and also with the NAMES OF THESE KEYS).

I poked at it and this patch seems to work well:

```patch
-  this.neat.input.on('pageup', () => { this.state.scrollback++ })
-  this.neat.input.on('pagedown', () => { this.state.scrollback = Math.max(0, this.state.scrollback - 1) })
+  this.neat.input.on('pageup', () => { this.state.scrollback += process.stdout.rows-10 })
+  this.neat.input.on('pagedown', () => { this.state.scrollback = Math.max(0, this.state.scrollback - (process.stdout.rows-10)) })
```

**Comment by cblgh** [comment]
@fabianhjr this has been unblocked! can you update neat-input to `^1.11.1` and i'll merge this one :3

**Comment by fabianhjr** [comment]
Hi @cblgh, done. :3

**Comment by cblgh** [comment]
@fabianhjr lovely! as a final final thing, can you document the nick scrolling in https://github.com/cabal-club/cabal-cli#hotkeys of the PR? 🖤 🖤

**Pull request merged**
