### PR TITLE
generate qr code with cabal key using /qr

### PR DESCRIPTION
**Pull request by cblgh**
i went ahead and implemented sharing of the cabal key via a QR code (thanks @dwblair for the inspiration!)

invoke the qr code using the `/qr` command

image

### CODE REVIEW

**Comment by nikolaiwarner** [comment]
🔥🔥🔥

**Comment by dwblair** [comment]
oooooooooooooooooooooh this is so coooooooooooooooooooool!!!!!

**Comment by noffle** [comment]
This is soooooooooooo cool.

It'd be another rad PR if we had a cli param like 'cabal --qr' that would use your laptop webcam to scan a code and then join that cabal.

**Comment by noffle** [comment]
/me expresses enthusiastic approval for y'all merging this :+1:

**Pull request merged**
