### PR TITLE
Add frontend configuration

### PR DESCRIPTION
**Pull request by quite**
Allow configuring of:
  - time format
  - indentation of message that are wrapped on a new line

### CODE REVIEW

**Comment by quite** [comment]
Hey! Here goes something :) It does not alter the current look of cabal-cli. But I do strongly prefer timeformat `'%H%M'` and indent `time` myself

**Comment by cblgh** [comment]
@quite wanna leave a screenshot of what it looks like for you? :)

**Comment by quite** [comment]
2020-03-23-144836_1148x1047_scrot

**Comment by cblgh** [comment]
@quite yeah fuck it, let's merge this. i'll take on the responsibility of rewriting things if the config gets out of hand later :~

can update the readme so that people know this option exists? maybe a small section under _Headless mode_ about configuring timestamps, with directions to read `.cabal.yml-example` for more information.

**Comment by quite** [comment]
Done!

**Comment by cblgh** [comment]
### 💯

**Pull request merged**
