### PR TITLE
replace --join with --save, add --cabals, fix multicabal joining

### LINKED ISSUE #161: config.yaml#cabals erased when passing key to cli
hey, i was wondering whether it is intentional that all cabals are replaced with the one provided on the command line when doing

$ cabal cabal://f4...c2

config.yaml before running cli:
```
aliases:
  cabal.club: 508fdfb25cc892e4ea32fe01be1a0d8cddd2a8bafae30aaf667446b1cdb220b9
cabals:
  - 508fdfb25cc892e4ea32fe01be1a0d8cddd2a8bafae30aaf667446b1cdb220b9
cache: {}
```

config.yaml after running cli:
```
aliases:
  cabal.club: 508fdfb25cc892e4ea32fe01be1a0d8cddd2a8bafae30aaf667446b1cdb220b9
cabals:
  - 'cabal://f4...c2'
cache: {}
```

i understand you do want to make a distinction between '--join key' (lasting) and providing a key as cli argument (single session). right?
this [comment](https://github.com/cabal-club/cabal-cli/blob/master/cli.js#L198) seems to second this, but storing the single session cabal and erasing the lasting ones  [this code](https://github.com/cabal-club/cabal-cli/blob/master/cli.js#L248) seems counter-productive. no?

let me know and i'll dig into this...

### PR DESCRIPTION
**Pull request by cblgh**
this pr adds the following flags:
`--save` saves a cabal to your config
`--cabals: lists the saved cabals in your config

--saved cabals are joined when cabal is invoked without arguments: `cabal`

the following flag has been removed:
`--join` previously joined the specific cabal while disregarding the config

the new behaviour is best explained by the examples below

```sh
# only join the passed in cabals
cabal cabal://key1 cabal://key2

# save the passed in cabal 
cabal --save cabal://key

# show saved cabals with --cabals
cabal --cabals

# remove a saved cabal using --forget
cabal --forget cabal://key

# join all of your saved cabals
cabal

# special case: if you don't have any saved cabals, we will save the first ones you run  e.g.
# if config empty, the following will persist the cabal to the config, first time only tho
cabal cabal://key # or
cabal --new
```

fixes #161 #158  also reverts PR #160 as it didn't work as expected. 

cc @tomquas here's the PR i promised! ^_^ it was a bit of an overhaul to get everything working inline with expectations. please check it out and let me know how things work!

### CODE REVIEW

**Comment by tomquas** [comment]
awesome, no more hosed config.yaml.

+1 for replacing --join w/ a cabal key argument.

cli still swallows a --join arg w/o effect, but i suppose this is sloppyness on minimist's side. cosmetics...

thanks for resolving this in no time...

**Comment by cblgh** [comment]
@tomquas re 
> cli still swallows a --join arg w/o effect, but i suppose this is sloppyness on minimist's side. cosmetics...

can you give me an example of what you run from the command line in regards to the above? not sure i understand completely atm

**Comment by tomquas** [comment]
> edit: or do you perhaps mean that --join doesn't cause an error, despite having been removed?

yes, that's what i meant; sorry for my sloppyness...

**Comment by cblgh** [comment]
no worries, and thanks for clarifying :3

**Pull request merged**
