### PR TITLE
delete character at cursor with ctrl-d

### LINKED ISSUE #142: have CTRL-D delete character, not close the program

### PR DESCRIPTION
**Pull request by nikolaiwarner**
fixes #142

### CODE REVIEW

**Comment by cblgh** [comment]
oh wait how did i miss this lol, i'll try to pull it down and verify it works on me compy and then merge

**Comment by noffle** [comment]
I fiddled with it a bit, and the first thing I tried was typing "hello" then hitting "CTRL-a" to go to the start of the line and hit "CTRL-d" several times, and my input line became permanently messed up.

I wonder if this'd make more sense as a patch to [neat-input](https://github.com/mafintosh/neat-input/blob/master/index.js#L62) that does input line management in the same way it does?

**Comment by quite** [comment]
I implemented delete in https://github.com/mafintosh/neat-input/pull/9

**Comment by quite** [comment]
When that goes in, I guess the solution here is to just drop specific handling of ctrl-d :)

**Comment by cblgh** [comment]
wooot that's amazing, thank you so much daniel!

for future reference: when Daniel's pr lands we should pin the new version
of neat-input, to ensure that it is correctly installed (had some issues
with that last year when a PR was merged upstream into neat-input)

**Comment by cblgh** [comment]
this has been fixed thanks to @quite! 

published in [cabal-cli@9.2.2](https://github.com/cabal-club/cabal-cli/releases/tag/v9.2.2)

**Comment by nikolaiwarner** [comment]
🔥🔥🔥🔥

**Pull request closed without merging**
