### PR TITLE
Upgrade standard to latest and lint it

### PR DESCRIPTION
**Pull request by quite**

### CODE REVIEW

**Comment by cblgh** [comment]
nice! thanks :) 

also: sorry for leaving https://github.com/cabal-club/cabal-cli/pull/151 in limbo! i haven't had time to make a decision on how (or rather _if_) to handle visual configs, it can get [messy quick](https://irssi.org/documentation/settings/)

**Comment by quite** [comment]
I know... I'm a happy user of weechat. I can tweak it to my hearts desire. But it's indeed nuts!

**Comment by quite** [comment]
Hm, gotta check this out..

**Comment by cblgh** [comment]
@quite can you add the following to `util.js` above the current line 14:
```js
  /*eslint no-control-regex: "off"*/
```

**Comment by cblgh** [comment]
thanks again! 🖤

**Pull request merged**
